// Comprehensive list of Indonesian cities (Kota) and major regencies (Kabupaten)
// Data compiled from various sources including official government data
export const indonesianCities = [
  "Ambon",
  "Balikpapan",
  "Banda Aceh",
  "Bandar Lampung",
  "Bandung",
  "Banjar",
  "Banjarbaru",
  "Banjarmasin",
  "Batam",
  "Batu",
  "Baubau",
  "Bekasi",
  "Bengkulu",
  "Bima",
  "Binjai",
  "Bitung",
  "Blitar",
  "Bogor",
  "Bontang",
  "Bukittinggi",
  "Cilegon",
  "Cimahi",
  "Cirebon",
  "Denpasar",
  "Depok",
  "Dumai",
  "Gorontalo",
  "Gunungsitoli",
  "Jakarta",
  "Jambi",
  "Jayapura",
  "Kediri",
  "Kendari",
  "Kotamobagu",
  "Kupang",
  "Langsa",
  "Lhokseumawe",
  "Lubuklinggau",
  "Madiun",
  "Magelang",
  "Makassar",
  "Malang",
  "Manado",
  "Mataram",
  "Medan",
  "Metro",
  "Mojokerto",
  "Padang",
  "Padang Panjang",
  "Padangsidimpuan",
  "Pagar Alam",
  "Palangkaraya",
  "Palembang",
  "Palopo",
  "Palu",
  "Pangkalpinang",
  "Parepare",
  "Pariaman",
  "Pasuruan",
  "Payakumbuh",
  "Pekalongan",
  "Pekanbaru",
  "Pematangsiantar",
  "Pontianak",
  "Prabumulih",
  "Probolinggo",
  "Sabang",
  "Salatiga",
  "Samarinda",
  "Sawah Lunto",
  "Semarang",
  "Serang",
  "Sibolga",
  "Singkawang",
  "Solok",
  "Sorong",
  "Subulussalam",
  "Sukabumi",
  "Sungai Penuh",
  "Surabaya",
  "Surakarta",
  "Tangerang",
  "Tangerang Selatan",
  "Tanjungbalai",
  "Tanjungpinang",
  "Tarakan",
  "Tasikmalaya",
  "Tebing Tinggi",
  "Tegal",
  "Ternate",
  "Tidore Kepulauan",
  "Tomohon",
  "Tual",
  "Yogyakarta",
].sort();
